#!/bin/bash
set -e

# Source profile
source ~/.profile

# Decrypt Secrets Config
sudo openssl enc -aes-256-cbc -md sha256 -d -in /portal/secrets.yml.enc -out /portal/secure/config.yml -k $KEY

# Check if newer image available
sudo docker pull icdocsoc/portal
# Run service
sudo docker stack deploy -c /portal/docker-compose.yml portal

# Cleanup unused resources
sudo docker image prune -a -f
sudo docker container prune -f
sudo docker volume prune -f
sudo docker network prune -f
